title: Gabriel's Portfolio
email: gacmartins@gmail.com
description: >-
  Neste site você encontrará meus projetos pessoais, habilidades práticas e informações de contato.
  <br>Sinta-se à vontade para explorar e conectar-se comigo, desde já agradeço a atenção!
baseurl: "" # Deixe vazio para GitHub Pages
url: "https://gabriel-dev-c.github.io" # Seu URL do GitHub Pages
linkedin_username: Gabriel C. Martins
github_username: Gabriel-Dev-C

# Build settings
theme: jekyll-theme-architect
plugins:
  - jekyll-feed

# Configurações adicionais recomendadas
# author:
  # name: Gabriel Chabaribery Martins
  # email: gacmartins@gmail.com

name: Gabriel Chabaribery Martins
location: São Paulo, Brasil
email: gacmartins@gmail.com

# Social media (opcional)
twitter_username: # seu usuário do Twitter (se tiver)
instagram_username: # seu usuário do Instagram (se tiver)

# Configurações de exibição
show_excerpts: true # Mostrar trechos dos posts na homepage